### ISSUE TITLE
UI problem in frontend 0.9.12-4-build-1132/ not all tags displayed

### ISSUE THREAD

**Issue by lcamelin** [realvnc-labs/rport#1074]
Hello, when creating a customer group and selecting the "has any tag" filter type, I don't see all the existing tags and I can't write in the field.

I am on debian 11 with "5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux".
The rport server is on version 0.9.12 and the frontend is rport-frontend-0.9.12-4-build-1132.

The rport sever run as a service without docker and no web proxy is used.

![image](https://github.com/realvnc-labs/rport/assets/84770080/d902a371-ea52-4655-8825-83a4e3b97f58)
![image](https://github.com/realvnc-labs/rport/assets/84770080/f9ae6f97-d13d-4eba-90d3-b5bf6a01cccf)

**Comment by thorstenkramm** [comment]
@lcamelin Thank you very much for reporting. I assume you have more than 50 tags. The frontend is fetching only the first 50, which is obviously wrong. A fix is underway. Hopefully, an update will be available on Monday.

**Comment by thorstenkramm** [comment]
@lcamelin This has been solved now.

Try updating the frontend to the latest version [frontend 0.9.12-5](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by lcamelin** [comment]
Sorry to say that but i still have the same problem even on rport-frontend-0.9.12-5-build-1133 . To make sure i even clear my cache lauch my webbrowser in private mode but i still have the problem that all tags is not showing in the tag selector on client groups.

Can i do something to give you more information on the problem ?

**Comment by thorstenkramm** [comment]
@lcamelin 
Please open the dev tools of your browser.
Select the network inspection.
Click on Settings->Client Groups
Check how the tags are fetched? Look for a request that goes to `client-tags?`.

<img width="1787" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/e49e8349-dc5c-4038-9997-9be052aba0c4">

**Comment by lcamelin** [comment]
OK thanks.
![image](https://github.com/realvnc-labs/rport/assets/84770080/806b4ec3-b3a7-4407-935d-32e27c929e6b)
We can see that it's fetch it as you show me but in the client group we can't see it.
![image](https://github.com/realvnc-labs/rport/assets/84770080/ef62ec9a-0488-4b96-a2fa-13f4be53a777)

can it be link to the fact its fail to show client groups correctly.
![image](https://github.com/realvnc-labs/rport/assets/84770080/2a3de76e-ef43-4963-a5a9-99cc151350fa)
![image](https://github.com/realvnc-labs/rport/assets/84770080/2153c552-7e2d-4657-be62-dd3b22a0316d)
i can see all the group but it make uncorrect showing when asking to show more with the right arrow.

**Comment by lcamelin** [comment]
oh and i forget to say that in 1133 the load more on dashboard not working.
![image](https://github.com/realvnc-labs/rport/assets/84770080/b2cd2830-38c5-4e1c-b9cb-c00762176acd)

**Comment by thorstenkramm** [comment]
@lcamelin I can't confirm the load more button isn't working.
Can you please open the dev tools and select the network inspection.
What happens behind the scenes when you click "load more"?

<img width="1233" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/7980106a-4545-464d-bb05-d894d51b6a21">

**Comment by thorstenkramm** [comment]
@lcamelin Please do not mix topics. This issue was about not all tags shown when creating a client group.
I can confirm the issue has not been fixed yet. All data is loaded but not displayed.

If the load more button on the client list is not working, please open a new issue for that.

**Comment by lcamelin** [comment]
yes sorry for the mixing its just to give the information on 1133. can i do something to find why its not showing all tags on the clien groups even when we see that it seem to call 500 as a limit ?

**Comment by thorstenkramm** [comment]
The issue is solved. Now all tags are loaded and available for selection.

Try updating the frontend to the latest version [frontend 0.9.12-6](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by lcamelin** [comment]
I confirm that the problem of tag selection in the client group is resolved.

Thank You, i will test the last version and open a new issued if i find a problem.

Have a nice day.
